variable "prefix" {}
variable "env" {}
variable "region" {}
variable "vpc_cidr_block" {}
variable "private_subnet_count" {}
variable "admin_workstation_ip" {}
variable "database_name" {}
variable "database_user" {}
variable "database_password" {}
variable "database_port" {}
variable "master_instance_type" {}
variable "worker_instance_type" {}
variable "asg_worker_nodes_min_size" {}
variable "asg_worker_nodes_max_size" {}